---
title: "chTKCat user guide"
author: "Patrice Godard"
date:  "`r format(Sys.time(), '%B %d, %Y')`"
output:
   html_document:
     number_sections: yes
     self_contained: yes
     theme: cerulean
     toc: yes
     toc_float: yes
vignette: >
   %\VignetteIndexEntry{chTKCat user guide}
   %\VignetteEncoding{UTF-8}
   %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, message=FALSE, echo=FALSE, include=FALSE, cache=FALSE}
library(knitr)
opts_chunk$set(
   include=TRUE,
   echo=TRUE,
   message=TRUE,
   warning=TRUE,
   cache=FALSE,
   cache.lazy=FALSE
)
library(devTKCat)
```

```{r child = 'supp/urls.Rmd'}
```


<!----------------------------------------------------------------------------->
<!----------------------------------------------------------------------------->
# Introduction

```{r child = 'supp/genIntro.Rmd'}
```

This vignette describes how TKCat can be used with
a [ClickHouse][clickhouse] database.
Users should also refer
to the [general TKCat user guide][uguide].
Finally, a [specific vignette][opman] describes
how to create and administrate a TKCat ClickHouse instance.
